import { PERMISSIONS, ROLES } from "./constants";

export const rolePermissions = {
	[ROLES.ADMIN]: [
		PERMISSIONS.CREATE_PRODUCTS,
		PERMISSIONS.UPDATE_PRODUCTS,
		PERMISSIONS.DELETE_PRODUCTS,
	],
	[ROLES.CUSTOMER]: [PERMISSIONS.READ_PROFILE, PERMISSIONS.UPDATE_PROFILE],
};
